### ISSUE TITLE
Ошибка при попытке отправки опечатки в своем топике

### ISSUE THREAD

**Issue by chiliec** [wyfinger/livestreet_mistakes#2]
Сейчас ничего не происходит после отправки. Предлагаю вообще выпилить возможность отправлять опечатки на собственные топики (ну бред же) и не давать вызывать модальное окно (можно дополнительно выводить ошибку c помощью [модуля системных сообщений](http://docs.livestreetcms.com/api/1.0/ModuleMessage)).

**Comment by wyfinger** [comment]
Почему бред, кто-то предпочитает делать заметки самому себе.
Хотя я с вами согласен, если запрещено - не нужно вообще попап показывать.

**Comment by chiliec** [comment]
С этими людьми явно не всё в порядке - легче ведь сразу исправить, чем самому же себе сообщать об ошибках в своем топике. 
Кроме того, такая функциональность несет в себе усложнение логики и возможные ошибки. Кроме того нужно быть уверенным что стандартное поведение модуля сообщений корректно обрабатывает беседу с самим собой, а там ещё куча зависимостей типа отправки сообщений на электронную почту. 
Собственно это и есть мои аргументы в сторону выпиливания этой возможности.

**Comment by chiliec** [comment]
Так что скажете?

**Comment by wyfinger** [comment]
Согласен, как раз сейчас отпиливаю это.

**Comment by chiliec** [comment]
:+1:
